apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: itw2
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: itw2
subjects:
- kind: ServiceAccount
  name: sa
  namespace: itw2
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: itw2
  name: deploy-reader
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-deploys
  namespace: itw2
subjects:
- kind: ServiceAccount
  name: sa
  namespace: itw2
roleRef:
  kind: ClusterRole
  name: deploy-reader
  apiGroup: rbac.authorization.k8s.io
